site_name: EspoCRM Documentation

repo_url: https://github.com/espocrm/documentation/

extra_javascript: [js/extra.js]

extra_css:
    - css/extra.css

markdown_extensions:
  - mdx_truly_sane_lists
  - codehilite:
      guess_lang: false
      use_pygments: true
  - toc:
      permalink: true
      toc_depth: 4

theme:
    name: material
    highlightjs: true
    palette:
        primary: blue grey
        accent: blue grey

nav:
    - 'Home': 'index.md'
    - 'Administration':
        - 'Server Configuration':
            - 'Configuration': 'administration/server-configuration.md'
            - 'Apache': 'administration/apache-server-configuration.md'
            - 'Nginx': 'administration/nginx-server-configuration.md'
        - 'System':
            - 'Installation': 'administration/installation.md'
            - 'Upgrading': 'administration/upgrading.md'
            - 'Extensions': 'administration/extensions.md'
            - 'Troubleshooting': 'administration/troubleshooting.md'
            - 'Console commands': 'administration/commands.md'
            - 'Jobs': 'administration/jobs.md'
            - 'WebSocket': 'administration/websocket.md'
            - 'Performance tweaking': 'administration/performance-tweaking.md'
            - 'Backup and restore': 'administration/backup-and-restore.md'
            - 'Moving to another server': 'administration/moving-to-another-server.md'
        - 'Customization':
            - 'Entity Manager': 'administration/entity-manager.md'
            - 'Fields': 'administration/fields.md'
            - 'Layouts': 'administration/layout-manager.md'
            - 'Dynamic forms': 'administration/dynamic-logic.md'
        - 'Roles management': 'administration/roles-management.md'
        - 'Email Administration': 'administration/emails.md'
        - 'Formula': 'administration/formula.md'
        - 'Import': 'administration/import.md'
        - 'Portal': 'administration/portal.md'
        - 'Currency': 'administration/currency.md'
        - 'Dashboards': 'administration/dashboards.md'
        - 'Authentication':
            - '2-factor authentication': 'administration/2fa.md'
            - 'LDAP':
                - 'Authorization': 'administration/ldap-authorization.md'
                - 'Active Directory': 'administration/ldap-authorization-for-ad.md'
                - 'OpenLDAP': 'administration/ldap-authorization-for-openldap.md'
        - 'Misc':
            - 'Terms & naming': 'administration/terms-and-naming.md'
            - 'Web-to-Lead': 'administration/web-to-lead.md'
            - 'Webhooks': 'administration/webhooks.md'
            - 'Maps': 'administration/maps.md'
            - 'B2C mode': 'administration/b2c.md'
            - 'Config params': 'administration/config-params.md'
            - 'Multiple assigned users': 'administration/multiple-assigned-users.md'
    - 'User Guide':
        - 'Emails':
            - 'General guidelines': 'user-guide/emails.md'
            - 'IMAP & SMTP configuration': 'user-guide/imap-smtp-configuration.md'
            - 'Mass Email': 'user-guide/mass-email.md'
        - 'Stream': 'user-guide/stream.md'
        - 'Sales management': 'user-guide/sales-management.md'
        - 'Case management': 'user-guide/case-management.md'
        - 'Activities & Calendar': 'user-guide/activities-and-calendar.md'
        - 'Mail Merge': 'user-guide/mail-merge.md'
        - 'Knowledge Base': 'user-guide/knowledge-base.md'
        - 'Documents': 'user-guide/documents.md'
        - 'Export': 'user-guide/export.md'
        - 'Text search': 'user-guide/text-search.md'
        - 'Misc':
            - 'Printing to PDF': 'user-guide/printing-to-pdf.md'
            - 'Markdown syntax': 'user-guide/markdown.md'
            - 'Browser support': 'user-guide/browser-support.md'
            - 'Data privacy': 'user-guide/data-privacy.md'
    - 'Extensions':
        - 'Advanced Pack':
            - 'Reports': 'user-guide/reports.md'
            - 'Workflows': 'administration/workflows.md'
            - 'Business Process Management': 'administration/bpm.md'
        - 'Sales Pack':
            - 'Products': 'user-guide/products.md'
            - 'Quotes': 'user-guide/quotes.md'
            - 'Sales Orders': 'user-guide/sales-orders.md'
            - 'Invoices': 'user-guide/invoices.md'
    - 'Developer Documentation': 'development/index.md'
